export type SeedDistillery = {
  name: string;
  region: string;
  country: string;
  source: string;
};

export type SeedBottle = {
  name: string;
  distillery: string;
  category: string;
  region: string;
  age?: number;
  abv?: number;
  notes?: string;
  source: string;
};

// Hand-curated catalog based on public distillery / brand product pages and
// a small amount of Wikipedia-style factual reference data for region mapping.
// We store only factual metadata useful for autocomplete and seed data.

const SOURCE = {
  ardbeg: "https://www.ardbeg.com/",
  arran: "https://www.arranwhisky.com/",
  auchentoshan: "https://www.auchentoshan.com/",
  aberfeldy: "https://www.aberfeldy.com/",
  aberlour: "https://www.aberlour.com/",
  balblair: "https://www.balblair.com/",
  balvenie: "https://www.thebalvenie.com/",
  benriach: "https://www.thebenriachdistillery.com/",
  benromach: "https://www.benromach.com/",
  bladnoch: "https://bladnoch.com/",
  blairAthol: "https://www.malts.com/en-row/products/blair-athol/",
  bowmore: "https://www.bowmore.com/",
  bruichladdich: "https://www.bruichladdich.com/",
  bunnahabhain: "https://bunnahabhain.com/",
  caolIla: "https://www.malts.com/en-row/products/caol-ila/",
  clynelish: "https://www.malts.com/en-row/products/clynelish/",
  craigellachie: "https://www.craigellachie.com/",
  cragganmore: "https://www.malts.com/en-row/products/cragganmore/",
  dalmore: "https://www.thedalmore.com/",
  dalwhinnie: "https://www.malts.com/en-row/products/dalwhinnie/",
  deanston: "https://deanstonmalt.com/",
  edradour: "https://edradour.com/",
  glenAllachie: "https://glenallachie.com/",
  glenDronach: "https://www.glendronachdistillery.com/",
  glenGrant: "https://theglengrant.com/",
  glenGoyne: "https://www.glengoyne.com/",
  glenKeith: "https://www.chivasbrothers.com/en/our-brands/glen-keith/",
  glenKinchie: "https://www.malts.com/en-row/products/glenkinchie/",
  glenlivet: "https://www.theglenlivet.com/",
  glenMoray: "https://www.glenmoray.com/",
  glenMorangie: "https://www.glenmorangie.com/",
  glenScotia: "https://www.glenscotia.com/",
  glenfiddich: "https://www.glenfiddich.com/",
  glenglassaugh: "https://www.glenglassaugh.com/",
  glengyle: "https://www.kilkerran.scot/",
  glenmfarclas: "https://www.glenfarclas.com/",
  glenrothes: "https://www.theglenrothes.com/",
  highlandPark: "https://www.highlandparkwhisky.com/",
  jura: "https://jurawhisky.com/",
  kilchoman: "https://www.kilchomandistillery.com/",
  lagavulin: "https://www.malts.com/en-row/products/lagavulin/",
  laphroaig: "https://www.laphroaig.com/",
  linkwood: "https://www.malts.com/en-row/products/linkwood/",
  lochLomond: "https://www.lochlomondwhiskies.com/",
  longmorn: "https://www.chivasbrothers.com/en/our-brands/longmorn/",
  macallan: "https://www.themacallan.com/",
  mortlach: "https://www.malts.com/en-row/products/mortlach/",
  oban: "https://www.malts.com/en-row/products/oban/",
  oldPulteney: "https://www.oldpulteney.com/",
  royalBrackla: "https://www.royalbrackla.com/",
  singletonDufftown: "https://www.thesingleton.com/en-row/our-whiskies/of-dufftown/",
  singletonGlenOrd: "https://www.thesingleton.com/en-row/our-whiskies/of-glen-ord/",
  springbank: "https://www.springbank.scot/",
  talisker: "https://www.malts.com/en-row/products/talisker/",
  tamdhu: "https://www.tamdhu.com/",
  tamnavulin: "https://www.tamnavulin.com/",
  tobermory: "https://tobermorydistillery.com/",
  tomatin: "https://tomatin.com/",
  tomintoul: "https://www.tomintoulwhisky.com/",
  ancnoc: "https://ancnoc.com/",
  cardhu: "https://www.malts.com/en-row/products/cardhu/",
  glencadam: "https://www.glencadamwhisky.com/",
  glenlossie: "https://www.malts.com/en-row/products/glenlossie/",
  glenturret: "https://theglenturret.com/",
  ncnean: "https://ncnean.com/",
  raasay: "https://raasaydistillery.com/",
  torabhaig: "https://torabhaig.com/",
  wolfburn: "https://wolfburn.com/",
  ardnamurchan: "https://www.ardnamurchandistillery.com/",
  glenburgie: "https://www.chivasbrothers.com/en/our-brands/glenburgie/",
  benrinnes: "https://www.malts.com/en-row/products/benrinnes/",
};

const distilleriesByRegion: Record<string, Array<{ name: string; source: string }>> = {
  Islay: [
    { name: "Ardbeg", source: SOURCE.ardbeg },
    { name: "Bowmore", source: SOURCE.bowmore },
    { name: "Bruichladdich", source: SOURCE.bruichladdich },
    { name: "Bunnahabhain", source: SOURCE.bunnahabhain },
    { name: "Caol Ila", source: SOURCE.caolIla },
    { name: "Kilchoman", source: SOURCE.kilchoman },
    { name: "Lagavulin", source: SOURCE.lagavulin },
    { name: "Laphroaig", source: SOURCE.laphroaig },
  ],
  Islands: [
    { name: "Arran", source: SOURCE.arran },
    { name: "Highland Park", source: SOURCE.highlandPark },
    { name: "Jura", source: SOURCE.jura },
    { name: "Raasay", source: SOURCE.raasay },
    { name: "Talisker", source: SOURCE.talisker },
    { name: "Tobermory", source: SOURCE.tobermory },
    { name: "Torabhaig", source: SOURCE.torabhaig },
  ],
  Campbeltown: [
    { name: "Glen Scotia", source: SOURCE.glenScotia },
    { name: "Glengyle", source: SOURCE.glengyle },
    { name: "Springbank", source: SOURCE.springbank },
  ],
  Lowlands: [
    { name: "Auchentoshan", source: SOURCE.auchentoshan },
    { name: "Bladnoch", source: SOURCE.bladnoch },
    { name: "Glenkinchie", source: SOURCE.glenKinchie },
  ],
  Highlands: [
    { name: "Aberfeldy", source: SOURCE.aberfeldy },
    { name: "anCnoc", source: SOURCE.ancnoc },
    { name: "Ardnamurchan", source: SOURCE.ardnamurchan },
    { name: "Balblair", source: SOURCE.balblair },
    { name: "Blair Athol", source: SOURCE.blairAthol },
    { name: "Clynelish", source: SOURCE.clynelish },
    { name: "Dalmore", source: SOURCE.dalmore },
    { name: "Dalwhinnie", source: SOURCE.dalwhinnie },
    { name: "Deanston", source: SOURCE.deanston },
    { name: "Edradour", source: SOURCE.edradour },
    { name: "GlenDronach", source: SOURCE.glenDronach },
    { name: "Glencadam", source: SOURCE.glencadam },
    { name: "Glenglassaugh", source: SOURCE.glenglassaugh },
    { name: "Glengoyne", source: SOURCE.glenGoyne },
    { name: "Glenmorangie", source: SOURCE.glenMorangie },
    { name: "Glenturret", source: SOURCE.glenturret },
    { name: "Loch Lomond", source: SOURCE.lochLomond },
    { name: "Nc'nean", source: SOURCE.ncnean },
    { name: "Oban", source: SOURCE.oban },
    { name: "Old Pulteney", source: SOURCE.oldPulteney },
    { name: "Royal Brackla", source: SOURCE.royalBrackla },
    { name: "Singleton of Glen Ord", source: SOURCE.singletonGlenOrd },
    { name: "Tomatin", source: SOURCE.tomatin },
    { name: "Wolfburn", source: SOURCE.wolfburn },
  ],
  Speyside: [
    { name: "Aberlour", source: SOURCE.aberlour },
    { name: "Benriach", source: SOURCE.benriach },
    { name: "Benrinnes", source: SOURCE.benrinnes },
    { name: "Benromach", source: SOURCE.benromach },
    { name: "Cardhu", source: SOURCE.cardhu },
    { name: "Craigellachie", source: SOURCE.craigellachie },
    { name: "Cragganmore", source: SOURCE.cragganmore },
    { name: "Glen Keith", source: SOURCE.glenKeith },
    { name: "Glen Moray", source: SOURCE.glenMoray },
    { name: "GlenAllachie", source: SOURCE.glenAllachie },
    { name: "Glenburgie", source: SOURCE.glenburgie },
    { name: "Glenfarclas", source: SOURCE.glenmfarclas },
    { name: "Glenfiddich", source: SOURCE.glenfiddich },
    { name: "GlenGrant", source: SOURCE.glenGrant },
    { name: "Glenlivet", source: SOURCE.glenlivet },
    { name: "Glenlossie", source: SOURCE.glenlossie },
    { name: "Glenrothes", source: SOURCE.glenrothes },
    { name: "Linkwood", source: SOURCE.linkwood },
    { name: "Longmorn", source: SOURCE.longmorn },
    { name: "Macallan", source: SOURCE.macallan },
    { name: "Mortlach", source: SOURCE.mortlach },
    { name: "Singleton of Dufftown", source: SOURCE.singletonDufftown },
    { name: "Tamdhu", source: SOURCE.tamdhu },
    { name: "Tamnavulin", source: SOURCE.tamnavulin },
    { name: "The Balvenie", source: SOURCE.balvenie },
    { name: "Tomintoul", source: SOURCE.tomintoul },
  ],
};

export const scotchDistilleries: SeedDistillery[] = Object.entries(distilleriesByRegion).flatMap(
  ([region, distilleries]) =>
    distilleries.map((distillery) => ({
      name: distillery.name,
      region,
      country: "Scotland",
      source: distillery.source,
    }))
);

const bottle = (
  name: string,
  distillery: string,
  region: string,
  source: string,
  options: Omit<SeedBottle, "name" | "distillery" | "region" | "category" | "source"> & {
    category?: string;
  } = {}
): SeedBottle => ({
  name,
  distillery,
  category: options.category ?? "Single Malt",
  region,
  age: options.age,
  abv: options.abv,
  notes: options.notes,
  source,
});

export const scotchBottles: SeedBottle[] = [
  // Islay
  bottle("Ardbeg 10 Year Old", "Ardbeg", "Islay", SOURCE.ardbeg, { age: 10, abv: 46, notes: "Core release" }),
  bottle("Ardbeg Wee Beastie 5 Year Old", "Ardbeg", "Islay", SOURCE.ardbeg, { age: 5, abv: 47.4, notes: "Core release" }),
  bottle("Ardbeg Uigeadail", "Ardbeg", "Islay", SOURCE.ardbeg, { abv: 54.2, notes: "NAS" }),
  bottle("Ardbeg Corryvreckan", "Ardbeg", "Islay", SOURCE.ardbeg, { abv: 57.1, notes: "NAS" }),
  bottle("Bowmore 12 Year Old", "Bowmore", "Islay", SOURCE.bowmore, { age: 12, abv: 40, notes: "Core release" }),
  bottle("Bowmore 15 Year Old", "Bowmore", "Islay", SOURCE.bowmore, { age: 15, abv: 43, notes: "Core release" }),
  bottle("Bowmore 18 Year Old", "Bowmore", "Islay", SOURCE.bowmore, { age: 18, abv: 43, notes: "Core release" }),
  bottle("Bruichladdich The Classic Laddie", "Bruichladdich", "Islay", SOURCE.bruichladdich, { abv: 50, notes: "NAS" }),
  bottle("Bruichladdich Islay Barley", "Bruichladdich", "Islay", SOURCE.bruichladdich, { abv: 50, notes: "Vintage release" }),
  bottle("Port Charlotte 10 Year Old", "Bruichladdich", "Islay", SOURCE.bruichladdich, { age: 10, abv: 50, notes: "Heavily peated" }),
  bottle("Octomore 14.1", "Bruichladdich", "Islay", SOURCE.bruichladdich, { abv: 59.6, notes: "Heavily peated series" }),
  bottle("Bunnahabhain 12 Year Old", "Bunnahabhain", "Islay", SOURCE.bunnahabhain, { age: 12, abv: 46.3, notes: "Core release" }),
  bottle("Bunnahabhain 18 Year Old", "Bunnahabhain", "Islay", SOURCE.bunnahabhain, { age: 18, abv: 46.3, notes: "Core release" }),
  bottle("Bunnahabhain Stiuireadair", "Bunnahabhain", "Islay", SOURCE.bunnahabhain, { abv: 46.3, notes: "NAS" }),
  bottle("Caol Ila 12 Year Old", "Caol Ila", "Islay", SOURCE.caolIla, { age: 12, abv: 43, notes: "Core release" }),
  bottle("Caol Ila Moch", "Caol Ila", "Islay", SOURCE.caolIla, { abv: 43, notes: "NAS" }),
  bottle("Caol Ila 18 Year Old", "Caol Ila", "Islay", SOURCE.caolIla, { age: 18, abv: 43, notes: "Core release" }),
  bottle("Kilchoman Machir Bay", "Kilchoman", "Islay", SOURCE.kilchoman, { abv: 46, notes: "NAS" }),
  bottle("Kilchoman Sanaig", "Kilchoman", "Islay", SOURCE.kilchoman, { abv: 46, notes: "NAS" }),
  bottle("Kilchoman Loch Gorm", "Kilchoman", "Islay", SOURCE.kilchoman, { abv: 46, notes: "Sherry cask release" }),
  bottle("Lagavulin 8 Year Old", "Lagavulin", "Islay", SOURCE.lagavulin, { age: 8, abv: 48, notes: "Core release" }),
  bottle("Lagavulin 16 Year Old", "Lagavulin", "Islay", SOURCE.lagavulin, { age: 16, abv: 43, notes: "Core release" }),
  bottle("Lagavulin Distillers Edition", "Lagavulin", "Islay", SOURCE.lagavulin, { abv: 43, notes: "Annual release" }),
  bottle("Laphroaig 10 Year Old", "Laphroaig", "Islay", SOURCE.laphroaig, { age: 10, abv: 40, notes: "Core release" }),
  bottle("Laphroaig Quarter Cask", "Laphroaig", "Islay", SOURCE.laphroaig, { abv: 48, notes: "NAS" }),
  bottle("Laphroaig Lore", "Laphroaig", "Islay", SOURCE.laphroaig, { abv: 48, notes: "NAS" }),
  bottle("Laphroaig 10 Year Old Cask Strength", "Laphroaig", "Islay", SOURCE.laphroaig, { age: 10, abv: 58.6, notes: "Batch-strength release" }),

  // Islands
  bottle("Arran 10 Year Old", "Arran", "Islands", SOURCE.arran, { age: 10, abv: 46, notes: "Core release" }),
  bottle("Arran Sherry Cask The Bodega", "Arran", "Islands", SOURCE.arran, { abv: 55.8, notes: "NAS" }),
  bottle("Arran Quarter Cask The Bothy", "Arran", "Islands", SOURCE.arran, { abv: 56.2, notes: "NAS" }),
  bottle("Highland Park 12 Year Old", "Highland Park", "Islands", SOURCE.highlandPark, { age: 12, abv: 40, notes: "Core release" }),
  bottle("Highland Park 18 Year Old", "Highland Park", "Islands", SOURCE.highlandPark, { age: 18, abv: 43, notes: "Core release" }),
  bottle("Highland Park Cask Strength", "Highland Park", "Islands", SOURCE.highlandPark, { abv: 63.3, notes: "Batch-strength release" }),
  bottle("Isle of Jura 10 Year Old", "Jura", "Islands", SOURCE.jura, { age: 10, abv: 40, notes: "Core release" }),
  bottle("Isle of Jura 12 Year Old", "Jura", "Islands", SOURCE.jura, { age: 12, abv: 40, notes: "Core release" }),
  bottle("Jura Seven Wood", "Jura", "Islands", SOURCE.jura, { abv: 42, notes: "NAS" }),
  bottle("Isle of Raasay Single Malt", "Raasay", "Islands", SOURCE.raasay, { abv: 46.4, notes: "Core release" }),
  bottle("Talisker 10 Year Old", "Talisker", "Islands", SOURCE.talisker, { age: 10, abv: 45.8, notes: "Core release" }),
  bottle("Talisker Skye", "Talisker", "Islands", SOURCE.talisker, { abv: 45.8, notes: "NAS" }),
  bottle("Talisker Storm", "Talisker", "Islands", SOURCE.talisker, { abv: 45.8, notes: "NAS" }),
  bottle("Talisker Port Ruighe", "Talisker", "Islands", SOURCE.talisker, { abv: 45.8, notes: "Port finish" }),
  bottle("Tobermory 12 Year Old", "Tobermory", "Islands", SOURCE.tobermory, { age: 12, abv: 46.3, notes: "Core release" }),
  bottle("Tobermory 18 Year Old", "Tobermory", "Islands", SOURCE.tobermory, { age: 18, abv: 46.3, notes: "Core release" }),
  bottle("Ledaig 10 Year Old", "Tobermory", "Islands", SOURCE.tobermory, { age: 10, abv: 46.3, notes: "Peated line" }),
  bottle("Ledaig Rioja Cask Finish", "Tobermory", "Islands", SOURCE.tobermory, { abv: 46.3, notes: "Wine cask finish" }),
  bottle("Torabhaig Allt Gleann", "Torabhaig", "Islands", SOURCE.torabhaig, { abv: 46, notes: "Core release" }),

  // Campbeltown
  bottle("Glen Scotia Double Cask", "Glen Scotia", "Campbeltown", SOURCE.glenScotia, { abv: 46, notes: "NAS" }),
  bottle("Glen Scotia 15 Year Old", "Glen Scotia", "Campbeltown", SOURCE.glenScotia, { age: 15, abv: 46, notes: "Core release" }),
  bottle("Glen Scotia Victoriana", "Glen Scotia", "Campbeltown", SOURCE.glenScotia, { abv: 54.2, notes: "NAS" }),
  bottle("Kilkerran 12 Year Old", "Glengyle", "Campbeltown", SOURCE.glengyle, { age: 12, abv: 46, notes: "Core release" }),
  bottle("Kilkerran Heavily Peated", "Glengyle", "Campbeltown", SOURCE.glengyle, { abv: 57.7, notes: "Batch release" }),
  bottle("Springbank 10 Year Old", "Springbank", "Campbeltown", SOURCE.springbank, { age: 10, abv: 46, notes: "Core release" }),
  bottle("Springbank 15 Year Old", "Springbank", "Campbeltown", SOURCE.springbank, { age: 15, abv: 46, notes: "Core release" }),
  bottle("Springbank 18 Year Old", "Springbank", "Campbeltown", SOURCE.springbank, { age: 18, abv: 46, notes: "Core release" }),
  bottle("Longrow Peated", "Springbank", "Campbeltown", SOURCE.springbank, { abv: 46, notes: "Peated line" }),
  bottle("Hazelburn 10 Year Old", "Springbank", "Campbeltown", SOURCE.springbank, { age: 10, abv: 46, notes: "Triple distilled line" }),

  // Lowlands
  bottle("Auchentoshan 12 Year Old", "Auchentoshan", "Lowlands", SOURCE.auchentoshan, { age: 12, abv: 40, notes: "Core release" }),
  bottle("Auchentoshan American Oak", "Auchentoshan", "Lowlands", SOURCE.auchentoshan, { abv: 40, notes: "NAS" }),
  bottle("Auchentoshan Three Wood", "Auchentoshan", "Lowlands", SOURCE.auchentoshan, { abv: 43, notes: "NAS" }),
  bottle("Bladnoch Vinaya", "Bladnoch", "Lowlands", SOURCE.bladnoch, { abv: 46.7, notes: "NAS" }),
  bottle("Bladnoch 11 Year Old", "Bladnoch", "Lowlands", SOURCE.bladnoch, { age: 11, abv: 46.7, notes: "Core release" }),
  bottle("Bladnoch Alinta", "Bladnoch", "Lowlands", SOURCE.bladnoch, { abv: 47, notes: "Peated release" }),
  bottle("Glenkinchie 12 Year Old", "Glenkinchie", "Lowlands", SOURCE.glenKinchie, { age: 12, abv: 43, notes: "Core release" }),
  bottle("Glenkinchie Distillers Edition", "Glenkinchie", "Lowlands", SOURCE.glenKinchie, { abv: 43, notes: "Annual release" }),

  // Highlands
  bottle("Aberfeldy 12 Year Old", "Aberfeldy", "Highlands", SOURCE.aberfeldy, { age: 12, abv: 40, notes: "Core release" }),
  bottle("Aberfeldy 15 Year Old", "Aberfeldy", "Highlands", SOURCE.aberfeldy, { age: 15, abv: 43, notes: "Core release" }),
  bottle("anCnoc 12 Year Old", "anCnoc", "Highlands", SOURCE.ancnoc, { age: 12, abv: 40, notes: "Core release" }),
  bottle("anCnoc 18 Year Old", "anCnoc", "Highlands", SOURCE.ancnoc, { age: 18, abv: 46, notes: "Core release" }),
  bottle("Ardnamurchan AD/", "Ardnamurchan", "Highlands", SOURCE.ardnamurchan, { abv: 46.8, notes: "Core release" }),
  bottle("Ardnamurchan AD/ Cask Strength", "Ardnamurchan", "Highlands", SOURCE.ardnamurchan, { abv: 58.3, notes: "Batch-strength release" }),
  bottle("Balblair 12 Year Old", "Balblair", "Highlands", SOURCE.balblair, { age: 12, abv: 46, notes: "Core release" }),
  bottle("Balblair 15 Year Old", "Balblair", "Highlands", SOURCE.balblair, { age: 15, abv: 46, notes: "Core release" }),
  bottle("Blair Athol 12 Year Old", "Blair Athol", "Highlands", SOURCE.blairAthol, { age: 12, abv: 43, notes: "Distillery bottling" }),
  bottle("Clynelish 14 Year Old", "Clynelish", "Highlands", SOURCE.clynelish, { age: 14, abv: 46, notes: "Core release" }),
  bottle("The Dalmore 12 Year Old", "Dalmore", "Highlands", SOURCE.dalmore, { age: 12, abv: 40, notes: "Core release" }),
  bottle("The Dalmore 15 Year Old", "Dalmore", "Highlands", SOURCE.dalmore, { age: 15, abv: 40, notes: "Core release" }),
  bottle("Dalwhinnie 15 Year Old", "Dalwhinnie", "Highlands", SOURCE.dalwhinnie, { age: 15, abv: 43, notes: "Core release" }),
  bottle("Dalwhinnie Distillers Edition", "Dalwhinnie", "Highlands", SOURCE.dalwhinnie, { abv: 43, notes: "Annual release" }),
  bottle("Deanston Virgin Oak", "Deanston", "Highlands", SOURCE.deanston, { abv: 46.3, notes: "NAS" }),
  bottle("Deanston 12 Year Old", "Deanston", "Highlands", SOURCE.deanston, { age: 12, abv: 46.3, notes: "Core release" }),
  bottle("Deanston 18 Year Old", "Deanston", "Highlands", SOURCE.deanston, { age: 18, abv: 46.3, notes: "Core release" }),
  bottle("Edradour 10 Year Old", "Edradour", "Highlands", SOURCE.edradour, { age: 10, abv: 40, notes: "Core release" }),
  bottle("Edradour Caledonia", "Edradour", "Highlands", SOURCE.edradour, { age: 12, abv: 46, notes: "Special release" }),
  bottle("GlenDronach 12 Year Old", "GlenDronach", "Highlands", SOURCE.glenDronach, { age: 12, abv: 43, notes: "Core release" }),
  bottle("GlenDronach 15 Year Old Revival", "GlenDronach", "Highlands", SOURCE.glenDronach, { age: 15, abv: 46, notes: "Core release" }),
  bottle("GlenDronach 18 Year Old Allardice", "GlenDronach", "Highlands", SOURCE.glenDronach, { age: 18, abv: 46, notes: "Core release" }),
  bottle("Glencadam 10 Year Old", "Glencadam", "Highlands", SOURCE.glencadam, { age: 10, abv: 46, notes: "Core release" }),
  bottle("Glencadam 15 Year Old", "Glencadam", "Highlands", SOURCE.glencadam, { age: 15, abv: 46, notes: "Core release" }),
  bottle("Glenglassaugh Revival", "Glenglassaugh", "Highlands", SOURCE.glenglassaugh, { abv: 46, notes: "Core release" }),
  bottle("Glenglassaugh Sandend", "Glenglassaugh", "Highlands", SOURCE.glenglassaugh, { abv: 50.5, notes: "Core release" }),
  bottle("Glengoyne 12 Year Old", "Glengoyne", "Highlands", SOURCE.glenGoyne, { age: 12, abv: 43, notes: "Core release" }),
  bottle("Glengoyne 15 Year Old", "Glengoyne", "Highlands", SOURCE.glenGoyne, { age: 15, abv: 43, notes: "Core release" }),
  bottle("Glenmorangie Original 12 Year Old", "Glenmorangie", "Highlands", SOURCE.glenMorangie, { age: 12, abv: 40, notes: "Core release" }),
  bottle("Glenmorangie Lasanta 12 Year Old", "Glenmorangie", "Highlands", SOURCE.glenMorangie, { age: 12, abv: 43, notes: "Sherry cask finish" }),
  bottle("Glenmorangie Quinta Ruban 14 Year Old", "Glenmorangie", "Highlands", SOURCE.glenMorangie, { age: 14, abv: 46, notes: "Port cask finish" }),
  bottle("Glenturret 10 Year Old", "Glenturret", "Highlands", SOURCE.glenturret, { age: 10, abv: 48.4, notes: "Core release" }),
  bottle("Glenturret 12 Year Old", "Glenturret", "Highlands", SOURCE.glenturret, { age: 12, abv: 46.4, notes: "Core release" }),
  bottle("Loch Lomond 12 Year Old", "Loch Lomond", "Highlands", SOURCE.lochLomond, { age: 12, abv: 46, notes: "Core release" }),
  bottle("Loch Lomond 18 Year Old", "Loch Lomond", "Highlands", SOURCE.lochLomond, { age: 18, abv: 46, notes: "Core release" }),
  bottle("Loch Lomond Inchmurrin 12 Year Old", "Loch Lomond", "Highlands", SOURCE.lochLomond, { age: 12, abv: 46, notes: "Single malt line" }),
  bottle("Nc'nean Organic Single Malt", "Nc'nean", "Highlands", SOURCE.ncnean, { abv: 46, notes: "Core release" }),
  bottle("Oban 14 Year Old", "Oban", "Highlands", SOURCE.oban, { age: 14, abv: 43, notes: "Core release" }),
  bottle("Oban Little Bay", "Oban", "Highlands", SOURCE.oban, { abv: 43, notes: "NAS" }),
  bottle("Old Pulteney 12 Year Old", "Old Pulteney", "Highlands", SOURCE.oldPulteney, { age: 12, abv: 40, notes: "Core release" }),
  bottle("Old Pulteney Huddart", "Old Pulteney", "Highlands", SOURCE.oldPulteney, { abv: 46, notes: "NAS" }),
  bottle("Royal Brackla 12 Year Old", "Royal Brackla", "Highlands", SOURCE.royalBrackla, { age: 12, abv: 40, notes: "Core release" }),
  bottle("The Singleton of Glen Ord 12 Year Old", "Singleton of Glen Ord", "Highlands", SOURCE.singletonGlenOrd, { age: 12, abv: 40, notes: "Core release" }),
  bottle("Tomatin 12 Year Old", "Tomatin", "Highlands", SOURCE.tomatin, { age: 12, abv: 43, notes: "Core release" }),
  bottle("Tomatin 14 Year Old Port Casks", "Tomatin", "Highlands", SOURCE.tomatin, { age: 14, abv: 46, notes: "Port cask finish" }),
  bottle("Tomatin Cask Strength", "Tomatin", "Highlands", SOURCE.tomatin, { abv: 57.5, notes: "Batch-strength release" }),
  bottle("Wolfburn Northland", "Wolfburn", "Highlands", SOURCE.wolfburn, { abv: 46, notes: "Core release" }),
  bottle("Wolfburn Aurora", "Wolfburn", "Highlands", SOURCE.wolfburn, { abv: 46, notes: "Sherry cask influenced" }),

  // Speyside
  bottle("Aberlour 12 Year Old", "Aberlour", "Speyside", SOURCE.aberlour, { age: 12, abv: 40, notes: "Core release" }),
  bottle("Aberlour 16 Year Old", "Aberlour", "Speyside", SOURCE.aberlour, { age: 16, abv: 43, notes: "Core release" }),
  bottle("Aberlour A'bunadh", "Aberlour", "Speyside", SOURCE.aberlour, { abv: 61.2, notes: "Batch-strength sherry cask" }),
  bottle("Benriach The Original Ten", "Benriach", "Speyside", SOURCE.benriach, { age: 10, abv: 43, notes: "Core release" }),
  bottle("Benriach The Smoky Ten", "Benriach", "Speyside", SOURCE.benriach, { age: 10, abv: 46, notes: "Peated release" }),
  bottle("Benriach The Twelve", "Benriach", "Speyside", SOURCE.benriach, { age: 12, abv: 46, notes: "Core release" }),
  bottle("Benrinnes 15 Year Old Flora & Fauna", "Benrinnes", "Speyside", SOURCE.benrinnes, { age: 15, abv: 43, notes: "Flora & Fauna release" }),
  bottle("Benromach 10 Year Old", "Benromach", "Speyside", SOURCE.benromach, { age: 10, abv: 43, notes: "Core release" }),
  bottle("Benromach 15 Year Old", "Benromach", "Speyside", SOURCE.benromach, { age: 15, abv: 43, notes: "Core release" }),
  bottle("Cardhu 12 Year Old", "Cardhu", "Speyside", SOURCE.cardhu, { age: 12, abv: 40, notes: "Core release" }),
  bottle("Cardhu Amber Rock", "Cardhu", "Speyside", SOURCE.cardhu, { abv: 40, notes: "NAS" }),
  bottle("Craigellachie 13 Year Old", "Craigellachie", "Speyside", SOURCE.craigellachie, { age: 13, abv: 46, notes: "Core release" }),
  bottle("Craigellachie 17 Year Old", "Craigellachie", "Speyside", SOURCE.craigellachie, { age: 17, abv: 46, notes: "Core release" }),
  bottle("Cragganmore 12 Year Old", "Cragganmore", "Speyside", SOURCE.cragganmore, { age: 12, abv: 40, notes: "Core release" }),
  bottle("Cragganmore Distillers Edition", "Cragganmore", "Speyside", SOURCE.cragganmore, { abv: 40, notes: "Annual release" }),
  bottle("Glen Keith 12 Year Old", "Glen Keith", "Speyside", SOURCE.glenKeith, { age: 12, abv: 43, notes: "Core release" }),
  bottle("Glen Moray 12 Year Old", "Glen Moray", "Speyside", SOURCE.glenMoray, { age: 12, abv: 40, notes: "Core release" }),
  bottle("Glen Moray 15 Year Old", "Glen Moray", "Speyside", SOURCE.glenMoray, { age: 15, abv: 40, notes: "Core release" }),
  bottle("GlenAllachie 12 Year Old", "GlenAllachie", "Speyside", SOURCE.glenAllachie, { age: 12, abv: 46, notes: "Core release" }),
  bottle("GlenAllachie 15 Year Old", "GlenAllachie", "Speyside", SOURCE.glenAllachie, { age: 15, abv: 46, notes: "Core release" }),
  bottle("GlenAllachie 10 Year Old Cask Strength", "GlenAllachie", "Speyside", SOURCE.glenAllachie, { age: 10, abv: 58.2, notes: "Batch-strength release" }),
  bottle("Glenburgie 15 Year Old Ballantine's Single Distillery", "Glenburgie", "Speyside", SOURCE.glenburgie, { age: 15, abv: 40, notes: "Single distillery release" }),
  bottle("Glenfarclas 12 Year Old", "Glenfarclas", "Speyside", SOURCE.glenmfarclas, { age: 12, abv: 43, notes: "Core release" }),
  bottle("Glenfarclas 15 Year Old", "Glenfarclas", "Speyside", SOURCE.glenmfarclas, { age: 15, abv: 46, notes: "Core release" }),
  bottle("Glenfarclas 105", "Glenfarclas", "Speyside", SOURCE.glenmfarclas, { abv: 60, notes: "Cask strength" }),
  bottle("Glenfiddich 12 Year Old", "Glenfiddich", "Speyside", SOURCE.glenfiddich, { age: 12, abv: 40, notes: "Core release" }),
  bottle("Glenfiddich 15 Year Old Solera", "Glenfiddich", "Speyside", SOURCE.glenfiddich, { age: 15, abv: 40, notes: "Solera vat" }),
  bottle("Glenfiddich 18 Year Old", "Glenfiddich", "Speyside", SOURCE.glenfiddich, { age: 18, abv: 40, notes: "Core release" }),
  bottle("The Glen Grant 10 Year Old", "GlenGrant", "Speyside", SOURCE.glenGrant, { age: 10, abv: 40, notes: "Core release" }),
  bottle("The Glen Grant 12 Year Old", "GlenGrant", "Speyside", SOURCE.glenGrant, { age: 12, abv: 43, notes: "Core release" }),
  bottle("The Glenlivet 12 Year Old", "Glenlivet", "Speyside", SOURCE.glenlivet, { age: 12, abv: 40, notes: "Core release" }),
  bottle("The Glenlivet 15 Year Old French Oak Reserve", "Glenlivet", "Speyside", SOURCE.glenlivet, { age: 15, abv: 40, notes: "French oak finish" }),
  bottle("The Glenlivet 18 Year Old", "Glenlivet", "Speyside", SOURCE.glenlivet, { age: 18, abv: 40, notes: "Core release" }),
  bottle("Glenlossie 10 Year Old Flora & Fauna", "Glenlossie", "Speyside", SOURCE.glenlossie, { age: 10, abv: 43, notes: "Flora & Fauna release" }),
  bottle("The Glenrothes 12 Year Old", "Glenrothes", "Speyside", SOURCE.glenrothes, { age: 12, abv: 40, notes: "Core release" }),
  bottle("The Glenrothes Whisky Maker's Cut", "Glenrothes", "Speyside", SOURCE.glenrothes, { abv: 48.8, notes: "NAS" }),
  bottle("Linkwood 12 Year Old Flora & Fauna", "Linkwood", "Speyside", SOURCE.linkwood, { age: 12, abv: 43, notes: "Flora & Fauna release" }),
  bottle("Longmorn 16 Year Old", "Longmorn", "Speyside", SOURCE.longmorn, { age: 16, abv: 48, notes: "Core release" }),
  bottle("Macallan 12 Year Old Double Cask", "Macallan", "Speyside", SOURCE.macallan, { age: 12, abv: 40, notes: "Core release" }),
  bottle("Macallan 12 Year Old Sherry Oak", "Macallan", "Speyside", SOURCE.macallan, { age: 12, abv: 40, notes: "Core release" }),
  bottle("Macallan 15 Year Old Double Cask", "Macallan", "Speyside", SOURCE.macallan, { age: 15, abv: 43, notes: "Core release" }),
  bottle("Mortlach 12 Year Old", "Mortlach", "Speyside", SOURCE.mortlach, { age: 12, abv: 43.4, notes: "Core release" }),
  bottle("Mortlach 16 Year Old", "Mortlach", "Speyside", SOURCE.mortlach, { age: 16, abv: 43.4, notes: "Core release" }),
  bottle("The Singleton of Dufftown 12 Year Old", "Singleton of Dufftown", "Speyside", SOURCE.singletonDufftown, { age: 12, abv: 40, notes: "Core release" }),
  bottle("Tamdhu 12 Year Old", "Tamdhu", "Speyside", SOURCE.tamdhu, { age: 12, abv: 43, notes: "Core release" }),
  bottle("Tamdhu 15 Year Old", "Tamdhu", "Speyside", SOURCE.tamdhu, { age: 15, abv: 46, notes: "Core release" }),
  bottle("Tamnavulin Double Cask", "Tamnavulin", "Speyside", SOURCE.tamnavulin, { abv: 40, notes: "NAS" }),
  bottle("Tamnavulin Sherry Cask Edition", "Tamnavulin", "Speyside", SOURCE.tamnavulin, { abv: 40, notes: "NAS" }),
  bottle("The Balvenie DoubleWood 12 Year Old", "The Balvenie", "Speyside", SOURCE.balvenie, { age: 12, abv: 40, notes: "Core release" }),
  bottle("The Balvenie Caribbean Cask 14 Year Old", "The Balvenie", "Speyside", SOURCE.balvenie, { age: 14, abv: 43, notes: "Rum cask finish" }),
  bottle("The Balvenie DoubleWood 17 Year Old", "The Balvenie", "Speyside", SOURCE.balvenie, { age: 17, abv: 43, notes: "Core release" }),
  bottle("Tomintoul 10 Year Old", "Tomintoul", "Speyside", SOURCE.tomintoul, { age: 10, abv: 40, notes: "Core release" }),
  bottle("Tomintoul 16 Year Old", "Tomintoul", "Speyside", SOURCE.tomintoul, { age: 16, abv: 40, notes: "Core release" }),
];
